name = "portfolio-api"
main = "src/index.ts"
compatibility_date = "2024-03-07"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "portfolio_db"
database_name = "portfolio-db"
database_id = "45b2459a-eae3-49ad-93fb-b8cc7b7065ad"

# R2 Bucket binding
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "portfolio-photos"

# Add CORS or env variables if needed
[vars]
# API_TOKEN = "Isabel-Photo2026"
